export const responseMessages: Record<string, string> = {
    "0002": "Missing Username Information",
    "0003": "Missing Password Information",
    "0004": "Missing Date Information",
    "0005": "Invalid Password",
    "0006": "User does not have an IntouchPay account",
    "0007": "No such user",
    "0008": "Failed to authenticate",
    "1100": "Error in request",
    "1101": "Service ID not recognized",
    "1102": "Invalid mobile phone number",
    "1103": "Payment above allowed maximum",
    "1104": "Payment below allowed minimum",
    "1105": "Network not supported",
    "1106": "Operation not permitted",
    "1107": "Payment account not configured",
    "1108": "Insufficient account balance",
    "1110": "Duplicate remit ID",
    "2001": "Request successful",
    "2003": "Transaction not allowed",
    "2102": "Subscriber could not be identified",
    "2105": "Non-existent mobile account",
    "2106": "Own mobile account provided",
    "2107": "Invalid amount format",
    "2108": "Insufficient funds on source account",
    "2109": "Daily Limit Exceeded",
    "2110": "Source Account Not Active",
    "2111": "Mobile Account Not Active",
    "2000": "General Failure",
    "2500": "Service Failure",
    "2510": "Service Temporarily Unavailable",
    "2518": "Could Not Perform Operation",
    "2520": "Incorrect Account Password",
    "2522": "Invalid Amount",
    "2600": "Network Failure - Request Timed Out",
    "2800": "Deposit Channel Failure"

};